# Generated by Django 2.2.16 on 2023-06-19 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230618_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Нужно хоть какое-то количество.'), django.core.validators.MaxValueValidator(20, 'Слишком много!')], verbose_name='Количество'),
        ),
    ]
