# Generated by Django 4.2.1 on 2023-06-06 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_carts',
            field=models.ManyToManyField(blank=True, related_name='shopping_carts', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
    ]
