# Generated by Django 2.2.16 on 2023-06-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230619_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='unit',
            new_name='amount',
        ),
    ]
