# Generated by Django 2.2.16 on 2023-06-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230619_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='amount',
            new_name='unit',
        ),
    ]
