# Generated by Django 2.2.16 on 2023-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230621_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='unit',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
