# Generated by Django 2.2.16 on 2023-06-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230623_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
