# Generated by Django 2.2.16 on 2023-06-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230623_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscriptions',
        ),
    ]
